language: node_js
node_js:
  - "0.12"
  - "0.11"
before_script:
  - npm install mocha
script:
  - npm test tests/unit/
  - npm test tests/basic/
  - npm run build
  - npm run clean
sudo: false
cache:
  directories:
    - node_modules
