language: node_js
node_js:
  - "0.12"
  - "4"
  - "stable"
before_script:
  - npm install browserify
  - npm install mocha
script:
  - npm test tests/unit/
  - npm test tests/basic/
  - npm test tests/testInstallPackage.js
  - npm run build-browser
  - npm run clean
sudo: false
cache:
  directories:
    - node_modules
